<template>
  <div class="page">
    <h2>Story Generator</h2>
    <p style="color: var(--text-muted); margin-bottom: 1rem">
      Generate complete reading worksheets with story, comprehension questions, vocabulary, and
      grammar exercises — all auto-generated by AI.
    </p>

    <div class="card" style="margin-bottom: 1rem">
      <div class="form-group">
        <label>Topic / Theme</label>
        <input v-model="form.topic" placeholder="e.g. A day at the farm, A space adventure..." />
      </div>
      <div style="display: flex; gap: 0.5rem">
        <div class="form-group" style="flex: 1">
          <label>Grade Level</label>
          <select v-model="form.gradeLevel">
            <option value="">-- Select --</option>
            <option v-for="g in gradeLevels" :key="g" :value="g">Grade {{ g }}</option>
          </select>
        </div>
        <div class="form-group" style="flex: 1">
          <label>Question Count</label>
          <select v-model.number="form.questionCount">
            <option :value="5">5</option>
            <option :value="8">8</option>
            <option :value="10">10</option>
            <option :value="15">15</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label>Grammar Focus (optional)</label>
        <input
          v-model="form.grammarFocus"
          placeholder="e.g. past tense, prepositions, adjectives..."
        />
      </div>
      <div class="form-group">
        <label>Vocabulary Words (comma-separated, optional)</label>
        <input v-model="form.vocabulary" placeholder="e.g. farm, barn, harvest, tractor..." />
      </div>
      <div style="display: flex; gap: 0.5rem">
        <label style="display: flex; align-items: center; gap: 0.25rem">
          <input type="checkbox" v-model="form.includeVocab" /> Vocabulary exercises
        </label>
        <label style="display: flex; align-items: center; gap: 0.25rem">
          <input type="checkbox" v-model="form.includeGrammar" /> Grammar exercises
        </label>
      </div>
      <div class="form-group" style="margin-top: 0.5rem">
        <label>AI Provider</label>
        <select v-model="form.provider">
          <option value="">Auto (backend default)</option>
          <option value="opencode">OpenCode</option>
          <option value="ollama">Ollama</option>
          <option value="gemini">Gemini</option>
        </select>
      </div>
      <button
        class="btn-primary"
        style="width: 100%; margin-top: 1rem"
        @click="generate"
        :disabled="generating"
      >
        {{ generating ? 'Generating...' : 'Generate Story Worksheet' }}
      </button>
    </div>

    <div v-if="generatedBlocks.length" class="card" style="margin-bottom: 1rem">
      <h3>Generated Blocks ({{ generatedBlocks.length }})</h3>
      <div style="display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap">
        <span v-for="b in generatedBlocks" :key="b.id" class="badge" style="margin-bottom: 0.25rem">
          {{ b.type }}
        </span>
      </div>
      <button class="btn-primary" style="margin-top: 0.5rem" @click="saveAsWorksheet">
        Save as Worksheet
      </button>
    </div>

    <div v-if="generatedBlocks.length" style="margin-top: 1rem">
      <h3>Preview</h3>
      <div
        v-for="block in generatedBlocks"
        :key="block.id"
        class="card"
        style="margin-bottom: 0.5rem"
      >
        <div style="display: flex; justify-content: space-between; margin-bottom: 0.5rem">
          <strong>{{ block.type.replace(/_/g, ' ') }}</strong>
          <span class="badge">{{ block.points }} pts</span>
        </div>
        <div v-if="block.type === 'text' || block.type === 'read_aloud'">
          <div style="white-space: pre-wrap; max-height: 200px; overflow-y: auto">
            {{ block.text }}
          </div>
        </div>
        <div v-else>
          <p><strong>Q:</strong> {{ block.text }}</p>
          <div v-if="block.options">
            <span
              v-for="(opt, oi) in block.options"
              :key="oi"
              class="badge"
              style="margin-right: 0.25rem; margin-bottom: 0.25rem"
              >{{ opt }}</span
            >
          </div>
          <div v-if="block.template">
            <code style="font-size: 0.85rem">{{ block.template }}</code>
          </div>
          <div v-if="block.vocabulary">
            <span
              v-for="p in block.vocabulary.pairs || block.vocabulary || []"
              :key="p.l"
              class="badge"
              style="margin-right: 0.25rem"
              >{{ p.l }} → {{ p.r }}</span
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../services/api'
import { useWorksheetsStore } from '../stores/worksheets'
import { useUiStore } from '../stores/ui'

const router = useRouter()
const wStore = useWorksheetsStore()
const uiStore = useUiStore()

const form = ref({
  topic: '',
  gradeLevel: '2',
  grammarFocus: '',
  vocabulary: '',
  questionCount: 5,
  includeVocab: true,
  includeGrammar: true,
  provider: '',
})

const gradeLevels = ref([])
const generating = ref(false)
const generatedBlocks = ref([])

onMounted(async () => {
  try {
    const data = await api.get('/worksheets/grade-levels')
    gradeLevels.value = data.gradeLevels || []
  } catch {
    /* */
  }
})

async function generate() {
  if (!form.value.topic.trim()) {
    uiStore.showToast('Please enter a topic', 'error')
    return
  }
  generating.value = true
  try {
    const data = await api.post('/ai/generate-story', { ...form.value })
    generatedBlocks.value = data.blocks || []
    uiStore.showToast(`Generated ${generatedBlocks.value.length} blocks!`, 'success')
  } catch (e) {
    uiStore.showToast(e.message, 'error')
  } finally {
    generating.value = false
  }
}

async function saveAsWorksheet() {
  try {
    const content = JSON.stringify({ blocks: generatedBlocks.value })
    const ws = await wStore.createWorksheet({
      title: `Story: ${form.value.topic}`,
      subject: 'German',
      grade_level: form.value.gradeLevel,
      content,
      total_points: generatedBlocks.value.reduce((s, b) => s + (b.points || 0), 0),
    })
    uiStore.showToast('Worksheet saved!', 'success')
    router.push(`/teacher/builder/${ws.id}`)
  } catch (e) {
    uiStore.showToast(e.message, 'error')
  }
}
</script>
